spring:
  profiles:
    active: dev

taskconfig:
  jobList[0]:
    jobName: SingleTask
    jobClass: com.bsi.service.timetask.job.SingleTask
    jobGroupName: test
    jobTime: 0 0/5 * * * ?
    status: true
  jobList[1]:
    jobName: BiYxqkTask
    jobClass: com.bsi.service.timetask.job.BiYxqkTask
    jobGroupName: test
    #    每个月最后一天执行
    jobTime: 0 0 0 L * ? *
    status: true